### ISSUE TITLE
UI elements not included to the screenshot

### ISSUE THREAD

**Issue by novavision** [ertanturan/Unity-Screenshot-Tool#2]
Just adding simple UI Image to the scene, it will not be saved to captured texture

**Comment by ertanturan** [comment]
Hey there !, 
Thanks for the feedback. Have you checked the demo ?
Is there any warning in console ?

Cheers!

**Comment by novavision** [comment]
I found that happens only if I use overlay canvas. Is there something to do with that limiation?

**Comment by ertanturan** [comment]
Making the screenshot capturing system wait for the frame (Wait for end of the frame) should solve it ...

**Comment by novavision** [comment]
Unfortunately it's not.. It's Unity limitations as I know now

**Comment by ertanturan** [comment]
If that's the issue here looks like we can't really do much about it. Because, we can't really change how unity renders layers...
